### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [1]:
# 1. Lista contenente numeri da 0 a 9
# Ciclo: 
lista = []
for i in range(8):
    lista.append(i)

# List comprehension
listaC = [i for i in range(8)]

print(lista)
print(listaC)

[0, 1, 2, 3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7]


In [2]:
# 2. Lista che ha i primi 5 numeri dispari
# Ciclo:
dispari = []
contatore = 1
i = 0
while contatore < 6:
    if i % 2 != 0:
        dispari.append(i)
        contatore += 1
    i += 1

# List comprehension:
dispariC = [i for i in range(25) if i % 2 != 0][:5]
print(dispari)
print(dispariC)

[1, 3, 5, 7, 9]
[1, 3, 5, 7, 9]


In [3]:
# 3. Lista che ha solo le parole che hanno la lettera 'a' al loro interno, della lista chiamata 'parole'
#Ciclo:
parole = ["ciao", "libro", "persona", "computer"]
lista = []

for parola in parole:
    if 'a' in parola:
        lista.append(parola)

#List comprehension:
paroleC = [parola for parola in parole if 'a' in parola]

print(lista)
print(paroleC)

['ciao', 'persona']
['ciao', 'persona']


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [10]:
# vettore contenente in numeri primi compresi tra 0 e 10
import numpy as np
vettore = np.array([2, 3, 5, 7])
print(vettore)

#conto quanti numeri ci sono nel vettore
print(len(vettore))
#conto quanti numeri ci sono nel vettore accedendo all'attributo size
print(vettore.size)
#il tipo di dato del vettore è intero perchè viene definito dai numeri che inseriamo e dalla gerarchia
print(vettore.dtype)
#scrivo l'array usando list comprehention che controlla che i numeri siano primi
#definisco prima una funzione che faccia da istruzione condizionale
def primo(x):
    cont = 0
    i = x
    while i > 0:
        if x % i == 0:
            cont += 1 #contatore che tiene il numero di divisori
        i -= 1
    return cont == 2 #ritorna true solo se x ha 2 divisori( 1 e se stesso)

vettoreC = np.array([i for i in range(11) if primo(i)])
print(vettoreC)

[2 3 5 7]
4
4
int64
[2 3 5 7]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [26]:
import numpy as np
#modo 1
#creo array da lista
#lista = []
#for i in range(1, 12): #range(11) = range(0,11)
    #lista.append(i)
#a = np.array(lista)
#modo 2
a = np.arange(1, 12)
print(a)
#creo array b contenente una sottostringa di a
b = a[3:8] #dall'indice 3 all'indice 8 escluso
print(b)

#creo l'array c che è il reverse di a
#c = np.flip(a)
c = a[::-1]
print(c)

#divido l'array a per l'array c
print(a/c)

##Analogamente per le liste
l1 = []
for i in range(1, 12): #range(11) = range(0,11)
    l1.append(i)
print(l1)
#slicing
b1 = l1[3:8]
print(b1)
#inverti
c1 = l1.copy()
c1.reverse()
print(c1)

#divisione
divisione = []
for i in range(0,11):
    divisione.append((l1[i])/c1[i])
print(divisione)


[ 1  2  3  4  5  6  7  8  9 10 11]
[4 5 6 7 8]
[11 10  9  8  7  6  5  4  3  2  1]
[ 0.09090909  0.2         0.33333333  0.5         0.71428571  1.
  1.4         2.          3.          5.         11.        ]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[4, 5, 6, 7, 8]
[11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[0.09090909090909091, 0.2, 0.3333333333333333, 0.5, 0.7142857142857143, 1.0, 1.4, 2.0, 3.0, 5.0, 11.0]
